# Generated by Django 2.0 on 2018-02-22 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tags', models.TextField()),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('urlembed', models.URLField()),
            ],
        ),
    ]
