# Generated by Django 2.0 on 2018-02-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180225_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='urlembed',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
