# Generated by Django 2.0 on 2018-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180225_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='', help_text='Url slugs', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
